kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      # Ichor-Api
      - containerPort: 8080
        hostPort: 8080
      # Ichor-Api debug
      - containerPort: 8090
        hostPort: 8090
      # Metrics
      - containerPort: 10000
        hostPort: 10000
      # Metrics debug
      - containerPort: 10010
        hostPort: 10010
      # Metrics Prometheus
      - containerPort: 10020
        hostPort: 10020
      # Auth
      - containerPort: 6000
        hostPort: 6000
      # Auth debug
      - containerPort: 6010
        hostPort: 6010
      # Grafana
      - containerPort: 3100
        hostPort: 3100
      # Postgres
      - containerPort: 5432
        hostPort: 5432
      # Prometheus
      - containerPort: 9090
        hostPort: 9090
      # Tempo (tracing)
      - containerPort: 9412
        hostPort: 9412
