apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-worker-config
  namespace: ichor-system
data:
  temporal_host: "temporal-service:7233"
  temporal_namespace: "default"
  rabbitmq_url: "amqp://guest:guest@rabbitmq-service:5672/"
