apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/workflow-worker/
  - ./dev-workflow-worker-configmap.yaml
patches:
  - path: ./dev-workflow-worker-patch-deploy.yaml
images:
  - name: workflow-worker-image
    newName: localhost/superior/workflow-worker
    newTag: 0.0.1
