apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ichor-system
data:
  db_host: "database-service"
  db_user: "postgres"
  db_password: "postgres"
  db_disabletls: "true"
  llm_provider: "ollama"
  llm_model: "qwen2.5:latest"
  llm_host: "http://host.docker.internal:11434"
